export const welcomeMessages = [
  'Merhaba',
  'Grüß Gott',
  'Namaskar',
  'Zdraveite',
  'Hola',
  'Hafa adai',
  'Nǐ hǎo',
  'Dobro Jutro = Good morning',
  'Dobar dan = Good day',
  'Dobra većer = Good evening',
  'God dag',
  'Hoi = Hi↵Hallo = Hello',
  'hyvää päivää',
  'Bonjour',
  'Dia dhuit',
  'Guten tag',
  'Yasou',
  'Shalom',
  'Namaste',
  'Jo napot',
  'Góðan dag',
  'Nde-ewo',
  'Selamat siang',
  'Salve',
  'Konnichiwa',
  'Ahn nyong ha se yo',
  'Salve',
  'Sveiki',
  'Moïen',
  'Bonġu',
  'Niltze',
  'Namastē',
  'Hallo',
  'Salam',
  'Cześć',
  'Olá',
  'Bună ziua',
  'Zdravstvuyte',
  'Zdravo',
  'Ahoj',
  'Hola',
  'Hujambo',
  'Hallå',
  'Ia orna',
  'Sawasdee',
  'Avuxeni',
  'Merhaba',
  'Zdravstvuyte',
  'Assalamo aleikum',
  'xin chào',
  'Shwmae',
  'Sawubona'
];
